name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
              with:
                  version: 0.17.0
            - run: zig build ci --summary all
            - run: zig build test --release=safe --summary all
            - run: zig build fuzz --release=safe -- smoke

    thread-sanitizer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
              with:
                  version: 0.17.0
            - run: zig build test -Dtsan=true --release=safe --summary all

    soak:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
              with:
                  version: 0.17.0
            - run: zig build soak --release=safe --summary all
